"""add password_reset_jti_expires_at to users

Revision ID: 0b19ff09313e
Revises: d7a8851380f6
Create Date: 2026-03-16 01:48:21.003860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b19ff09313e'
down_revision: Union[str, Sequence[str], None] = 'd7a8851380f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_jti_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_jti_expires_at')
    # ### end Alembic commands ###
