"""add is_disabled to users

Revision ID: aefe6b5ec3a1
Revises: 319bd11888b9
Create Date: 2026-03-21 16:46:42.579022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefe6b5ec3a1'
down_revision: Union[str, Sequence[str], None] = '319bd11888b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    # ### end Alembic commands ###
