"""add opaque email verification and password reset code columns

Revision ID: ce824630f5cd
Revises: 0b19ff09313e
Create Date: 2026-03-16 01:58:57.263233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce824630f5cd'
down_revision: Union[str, Sequence[str], None] = '0b19ff09313e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_code_expires_at')
    op.drop_column('users', 'password_reset_code')
    op.drop_column('users', 'email_verification_code_expires_at')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ###
