"""add index on password_reset_jti column

Revision ID: cf997718a679
Revises: ce824630f5cd
Create Date: 2026-03-16 02:46:27.069308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf997718a679'
down_revision: Union[str, Sequence[str], None] = 'ce824630f5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_password_reset_jti'), 'users', ['password_reset_jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_jti'), table_name='users')
    # ### end Alembic commands ###
